/** Verdant Scholar tokens mirror the Stitch export for "The Living Archive" editorial UI. */
export const verdantScholarTokens = {
  colors: {
    primary: "#3f6a00",
    onPrimary: "#ffffff",
    primaryContainer: "#8cc24d",
    onPrimaryContainer: "#2d4d00",
    primaryFixed: "#baf478",
    primaryFixedDim: "#9fd75f",
    secondary: "#496640",
    onSecondary: "#ffffff",
    secondaryContainer: "#caecbc",
    onSecondaryContainer: "#4f6c45",
    tertiary: "#6b5f00",
    onTertiary: "#ffffff",
    tertiaryContainer: "#c4b44f",
    onTertiaryContainer: "#4e4500",
    tertiaryFixed: "#f6e479",
    tertiaryFixedDim: "#d8c860",
    surface: "#fcf9f8",
    surfaceBright: "#fcf9f8",
    surfaceDim: "#dcd9d9",
    surfaceVariant: "#e5e2e1",
    surfaceContainerLowest: "#ffffff",
    surfaceContainerLow: "#f6f3f2",
    surfaceContainer: "#f0eded",
    surfaceContainerHigh: "#eae7e7",
    surfaceContainerHighest: "#e5e2e1",
    onSurface: "#1c1b1b",
    onSurfaceVariant: "#434939",
    outline: "#737968",
    outlineVariant: "#c2c9b4",
    background: "#fcf9f8",
    onBackground: "#1c1b1b",
    error: "#ba1a1a",
    errorContainer: "#ffdad6",
    onError: "#ffffff",
    onErrorContainer: "#93000a",
    inverseSurface: "#313030",
    inverseOnSurface: "#f3f0ef",
    inversePrimary: "#9fd75f",
    surfaceTint: "#3f6a00",
  },
  gradients: {
    primary: "linear-gradient(135deg, #3f6a00 0%, #8cc24d 100%)",
    glass:
      "linear-gradient(180deg, rgba(252, 249, 248, 0.86) 0%, rgba(252, 249, 248, 0.56) 100%)",
  },
  radii: {
    xs: "0.25rem",
    sm: "0.5rem",
    md: "0.75rem",
    xl: "1.5rem",
    pill: "9999px",
  },
  shadows: {
    ambient: "0 24px 48px rgba(28, 27, 27, 0.04)",
    floating: "0 18px 48px rgba(28, 27, 27, 0.08)",
    focus: "0 0 0 2px rgba(63, 106, 0, 0.4)",
  },
  spacing: {
    outer: "2rem",
    section: "3rem",
    panel: "2rem",
    compact: "1rem",
  },
  typography: {
    displayLg: "clamp(3.5rem, 8vw, 5.5rem)",
    displayMd: "clamp(2.4rem, 5vw, 4rem)",
    headlineMd: "1.75rem",
    headlineSm: "1.25rem",
    bodyLg: "1rem",
    bodyMd: "0.9375rem",
    labelMd: "0.75rem",
    labelSm: "0.625rem",
  },
  fonts: {
    display: '"Manrope", "Arial Narrow", "Avenir Next", sans-serif',
    body: '"Inter", "Helvetica Neue", Arial, sans-serif',
    label: '"Inter", "Helvetica Neue", Arial, sans-serif',
  },
  layout: {
    maxWidth: "96rem",
    sidebarWidth: "18rem",
  },
} as const;

/** CSS variables used by the scoped Verdant Scholar theme wrapper. */
export const verdantScholarThemeVariables = {
  "--vs-color-primary": verdantScholarTokens.colors.primary,
  "--vs-color-on-primary": verdantScholarTokens.colors.onPrimary,
  "--vs-color-primary-container": verdantScholarTokens.colors.primaryContainer,
  "--vs-color-on-primary-container":
    verdantScholarTokens.colors.onPrimaryContainer,
  "--vs-color-primary-fixed": verdantScholarTokens.colors.primaryFixed,
  "--vs-color-primary-fixed-dim": verdantScholarTokens.colors.primaryFixedDim,
  "--vs-color-secondary": verdantScholarTokens.colors.secondary,
  "--vs-color-on-secondary": verdantScholarTokens.colors.onSecondary,
  "--vs-color-secondary-container":
    verdantScholarTokens.colors.secondaryContainer,
  "--vs-color-on-secondary-container":
    verdantScholarTokens.colors.onSecondaryContainer,
  "--vs-color-tertiary": verdantScholarTokens.colors.tertiary,
  "--vs-color-on-tertiary": verdantScholarTokens.colors.onTertiary,
  "--vs-color-tertiary-container":
    verdantScholarTokens.colors.tertiaryContainer,
  "--vs-color-on-tertiary-container":
    verdantScholarTokens.colors.onTertiaryContainer,
  "--vs-color-tertiary-fixed": verdantScholarTokens.colors.tertiaryFixed,
  "--vs-color-tertiary-fixed-dim": verdantScholarTokens.colors.tertiaryFixedDim,
  "--vs-color-surface": verdantScholarTokens.colors.surface,
  "--vs-color-surface-bright": verdantScholarTokens.colors.surfaceBright,
  "--vs-color-surface-dim": verdantScholarTokens.colors.surfaceDim,
  "--vs-color-surface-variant": verdantScholarTokens.colors.surfaceVariant,
  "--vs-color-surface-container-lowest":
    verdantScholarTokens.colors.surfaceContainerLowest,
  "--vs-color-surface-container-low":
    verdantScholarTokens.colors.surfaceContainerLow,
  "--vs-color-surface-container": verdantScholarTokens.colors.surfaceContainer,
  "--vs-color-surface-container-high":
    verdantScholarTokens.colors.surfaceContainerHigh,
  "--vs-color-surface-container-highest":
    verdantScholarTokens.colors.surfaceContainerHighest,
  "--vs-color-on-surface": verdantScholarTokens.colors.onSurface,
  "--vs-color-on-surface-variant": verdantScholarTokens.colors.onSurfaceVariant,
  "--vs-color-outline": verdantScholarTokens.colors.outline,
  "--vs-color-outline-variant": verdantScholarTokens.colors.outlineVariant,
  "--vs-color-background": verdantScholarTokens.colors.background,
  "--vs-color-on-background": verdantScholarTokens.colors.onBackground,
  "--vs-color-error": verdantScholarTokens.colors.error,
  "--vs-color-error-container": verdantScholarTokens.colors.errorContainer,
  "--vs-color-on-error": verdantScholarTokens.colors.onError,
  "--vs-color-on-error-container": verdantScholarTokens.colors.onErrorContainer,
  "--vs-color-inverse-surface": verdantScholarTokens.colors.inverseSurface,
  "--vs-color-inverse-on-surface": verdantScholarTokens.colors.inverseOnSurface,
  "--vs-color-inverse-primary": verdantScholarTokens.colors.inversePrimary,
  "--vs-color-surface-tint": verdantScholarTokens.colors.surfaceTint,
  "--vs-gradient-primary": verdantScholarTokens.gradients.primary,
  "--vs-gradient-glass": verdantScholarTokens.gradients.glass,
  "--vs-radius-xs": verdantScholarTokens.radii.xs,
  "--vs-radius-sm": verdantScholarTokens.radii.sm,
  "--vs-radius-md": verdantScholarTokens.radii.md,
  "--vs-radius-xl": verdantScholarTokens.radii.xl,
  "--vs-radius-pill": verdantScholarTokens.radii.pill,
  "--vs-shadow-ambient": verdantScholarTokens.shadows.ambient,
  "--vs-shadow-floating": verdantScholarTokens.shadows.floating,
  "--vs-shadow-focus": verdantScholarTokens.shadows.focus,
  "--vs-space-outer": verdantScholarTokens.spacing.outer,
  "--vs-space-section": verdantScholarTokens.spacing.section,
  "--vs-space-panel": verdantScholarTokens.spacing.panel,
  "--vs-space-compact": verdantScholarTokens.spacing.compact,
  "--vs-font-display-lg": verdantScholarTokens.typography.displayLg,
  "--vs-font-display-md": verdantScholarTokens.typography.displayMd,
  "--vs-font-headline-md": verdantScholarTokens.typography.headlineMd,
  "--vs-font-headline-sm": verdantScholarTokens.typography.headlineSm,
  "--vs-font-body-lg": verdantScholarTokens.typography.bodyLg,
  "--vs-font-body-md": verdantScholarTokens.typography.bodyMd,
  "--vs-font-label-md": verdantScholarTokens.typography.labelMd,
  "--vs-font-label-sm": verdantScholarTokens.typography.labelSm,
  "--vs-font-display-family": verdantScholarTokens.fonts.display,
  "--vs-font-body-family": verdantScholarTokens.fonts.body,
  "--vs-font-label-family": verdantScholarTokens.fonts.label,
  "--vs-layout-max-width": verdantScholarTokens.layout.maxWidth,
  "--vs-layout-sidebar-width": verdantScholarTokens.layout.sidebarWidth,
} as const;
